### PR TITLE
Add new baat on 'code rebase' and new 'shaktiman' image

### PR DESCRIPTION
**Pull request by AshBardhan**
**Screenshots**
screen shot 2015-12-09 at 5 12 33 pm

### CODE REVIEW

**Comment by AshBardhan** [comment]
Mobile View
screen shot 2015-12-09 at 5 19 56 pm

**Comment by AshBardhan** [comment]
THEHRO !! @softvar @rachitGulati @djadmin @chinchang 
Iss PR ko dekhna anivaarya hai.

**Comment by chinchang** [comment]
+1

**Comment by chinchang** [comment]
@AshBardhan img only showing on homepage. Please check

**Pull request merged**
